apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: dev
  labels:
    app: my-web-app
spec:
    replicas: 2
    selector:
      matchLabels:
        app: my-web-app
    template:
      metadata:
        labels:
          app: my-web-app
      spec:
        containers:
          - name: my-web-app
            image: 879467241318.dkr.ecr.us-east-1.amazonaws.com/web-app
            ports:
              - containerPort: 8080
        imagePullSecrets:
          - name: ecr-secret
